language: objective-c
osx_image: xcode8.3
cache: false
sudo: false
rvm:
  - 2.4.0
before_install:
  - gem install bundler
  - bundle install --without=documentation
  - bundle exec pod install --repo-update
script:
  - set -o pipefail && xcodebuild test -workspace UnderControl.xcworkspace -scheme 'UnderControlTests-macOS' | xcpretty
  - set -o pipefail && xcodebuild test -workspace UnderControl.xcworkspace -scheme 'UnderControlTests-iOS' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' ONLY_ACTIVE_ARCH=NO | xcpretty
