disabled_rules:
  - force_try
  - force_cast
  - force_unwrapping
  - line_length
  - valid_docs
  - function_body_length
  - file_length
  - type_body_length

opt_in_rules:
  - empty_count
  - vertical_whitespace

variable_name:
  excluded:
    - id
    - URL
    - to
    - rx
    - x
    - y
    - z
